[cookie]
name = "graus_auth"
key = "cambia_questa_chiave_random_lunga"
expiry_days = 1

[credentials]

[credentials.usernames.merch]
name = "Merch"
password = "REPLACE_WITH_HASH_merch"

[credentials.usernames.fdefazio]
name = "Francesco Defazio"
password = "REPLACE_WITH_HASH_fdefazio"

[credentials.usernames.kristin]
name = "Kristin"
password = "REPLACE_WITH_HASH_kristin"

[credentials.usernames.silvia]
name = "Silvia"
password = "REPLACE_WITH_HASH_silvia"

[credentials.usernames.angelo]
name = "Angelo"
password = "REPLACE_WITH_HASH_angelo"

[credentials.usernames.peppi]
name = "Peppi"
password = "REPLACE_WITH_HASH_peppi"

[credentials.usernames.luca]
name = "Luca"
password = "REPLACE_WITH_HASH_luca"

[credentials.usernames.david]
name = "David"
password = "REPLACE_WITH_HASH_david"
